server:
  port: 8061
spring:
  application:
    name: cloud-user
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 121.196.55.80:8848
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.196.55.80:3306/my_blog?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false&seUnicode=true
    username: root
    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
config:
  jwt:
    # 加密密钥
    secret: dongdedoudong
    # token有效时长
    expire: 3600
    # header 名称
    header: token
