server:
  port: 8062
spring:
  application:
    name: cloud-blog
  cloud:
    nacos:
      discovery:
        server-addr: 121.196.55.80:8848
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.196.55.80:3306/myblog?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false&seUnicode=true
    username: root
    password: 123456
  jpa:
    #配置jpa的默认引擎为innoDB
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming:
        #遇到大写字母 加"_"的命名
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy