server:
  port: 8062
spring:
  application:
    name: cloud-blog
  cloud:
    nacos:
      discovery:
        server-addr: 121.196.55.80:8848
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.196.55.80:3306/my_blog?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false&seUnicode=true
    username: root
    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0